"""added username change limit

Revision ID: a209b60d4e34
Revises: 54ef12cbc961
Create Date: 2018-05-16 00:10:47.436268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a209b60d4e34'
down_revision = '54ef12cbc961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username_last_changed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username_last_changed')
    # ### end Alembic commands ###
