"""added Likes

Revision ID: 5803d2c4f294
Revises: fdc06ebb838d
Create Date: 2018-05-16 16:00:21.316105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5803d2c4f294'
down_revision = 'fdc06ebb838d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_like_post_id'), 'like', ['post_id'], unique=False)
    op.create_index(op.f('ix_like_timestamp'), 'like', ['timestamp'], unique=False)
    op.create_index(op.f('ix_like_user_id'), 'like', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_like_user_id'), table_name='like')
    op.drop_index(op.f('ix_like_timestamp'), table_name='like')
    op.drop_index(op.f('ix_like_post_id'), table_name='like')
    op.drop_table('like')
    # ### end Alembic commands ###
