"""empty message

Revision ID: c0d607a8b701
Revises: 5803d2c4f294
Create Date: 2018-05-16 19:21:58.410583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d607a8b701'
down_revision = '5803d2c4f294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'like', 'comment', ['comment_id'], ['id'])
    op.add_column('user', sa.Column('banned', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('post_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_post_count'), 'user', ['post_count'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_post_count'), table_name='user')
    op.drop_column('user', 'post_count')
    op.drop_column('user', 'banned')
    op.drop_constraint(None, 'like', type_='foreignkey')
    # ### end Alembic commands ###
